window.onload = function() {
	let myLiffId = "1653653755-0Gn4JzO5";
	initializeLiffOrDie(myLiffId);
};

/**
* Check if myLiffId is null. If null do not initiate liff.
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiffOrDie(myLiffId) {
	if (!myLiffId) {
		document.getElementById("liffAppContent").classList.add('hidden');
		document.getElementById("liffIdErrorMessage").classList.remove('hidden');
	} else {
		initializeLiff(myLiffId);
	}
}

/**
* Initialize LIFF
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiff(myLiffId) {
	liff.init({
		liffId: myLiffId
		})
		.then(() => {
			// start to use LIFF's api
			initializeApp();
		})
		.catch((err) => {
			console.log(err);
			document.getElementById("liffAppContent").classList.add('hidden');
			document.getElementById("liffInitErrorMessage").classList.remove('hidden');
		}
	);
}

/**
 * Initialize the app by calling functions handling individual app components
 */
function initializeApp() {
	displayLiffData();
	displayIsInClientInfo();
	registerButtonHandlers();

	// check if the user is logged in/out, and disable inappropriate button
	if (liff.isLoggedIn()) {
		document.getElementById("liffIsLogout").classList.add('hidden');
		document.getElementById("liffIsLogin").classList.remove('hidden');

		document.getElementById('liffLoginButton').disabled = true;
	} else {
		document.getElementById("liffIsLogout").classList.remove('hidden');
		document.getElementById("liffIsLogin").classList.add('hidden');

		document.getElementById('liffLogoutButton').disabled = true;
	}
}

/**
* Display data generated by invoking LIFF methods
*/
function displayLiffData() {
	document.getElementById('isInClient').textContent = liff.isInClient();
}

/**
* Toggle the login/logout buttons based on the isInClient status, and display a message accordingly
*/
function displayIsInClientInfo() {
	if (liff.isInClient()) {
		document.getElementById('liffIsLogin').classList.toggle('hidden');
		document.getElementById('liffIsLogout').classList.toggle('hidden');

		document.getElementById('liffLoginButton').classList.toggle('hidden');
		document.getElementById('liffLogoutButton').classList.toggle('hidden');

		document.getElementById('isInClientMessage').textContent = 'You are opening the app in the in-app browser of LINE.';
	} else {
		document.getElementById('isInClientMessage').textContent = 'You are opening the app in an external browser.';
	}
}

function registerButtonHandlers() {
	document.getElementById('openWindowButton').addEventListener('click', function() {
		liff.openWindow({
			url: 'https://submissionliff.herokuapp.com/', // Isi dengan Endpoint URL aplikasi web Anda
			external: true
		});
	});

	document.getElementById('closeWindowButton').addEventListener('click', function() {
		if (!liff.isInClient()) {
			// sendAlertIfNotInClient();
			alert("Not in Client.");
		} else {
			liff.closeWindow();
		}
	});

	// document.getElementById('sendMessageButton').addEventListener('click', function() {
	// 	if (!liff.isInClient()) {
	// 		alert("Not in Client.");
	// 	} else {
	// 		liff.sendMessages([{
	// 			'type': 'text',
	// 			'text': "You've successfully sent a message! Hooray!"
	// 		}]).then(function() {
	// 			window.alert('Message sent');
	// 		}).catch(function(error) {
	// 			window.alert('Error sending message: ' + error);
	// 		});
	// 	}
	// });

	document.getElementById('liffLoginButton').addEventListener('click', function() {
		if (!liff.isLoggedIn()) {
			liff.login();
		}
	});

	document.getElementById('liffLogoutButton').addEventListener('click', function() {
		if (liff.isLoggedIn()) {
			liff.logout();
			window.location.reload();
		}
	});
}

function sendMessage(movieName) {
	if (!liff.isInClient()) {
		alert("Not in Client.");
	} else {
		liff.sendMessages([{
			'type': 'text',
			'text': "Movie: " + movieName
		}]).then(function() {
			window.alert("Hooray! You've successfully sent a message!");
		}).catch(function(error) {
			window.alert('Error: ' + error);
		});
	}
}
